/**
 * MERN E-Commerce Project Template Generator
 * Generates a complete, functional, runnable MERN e-commerce application
 * with Core features (Auth, Cart, Orders) + Selected Optional modules (Products, Payments, Reviews).
 */

export function generateMernStoreFiles(config = {}) {
  const storeName = config.name || config.store?.name || 'Bloom Boutique';
  const slug = storeName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const currency = config.currency || config.store?.currency || 'INR';
  const currencySymbol = currency === 'USD' ? '$' : currency === 'EUR' ? '€' : currency === 'GBP' ? '£' : '₹';
  const themeColor = config.theme || config.store?.theme || '#2383E2';

  const selectedModules = config.selectedModules || config.modules || ['products', 'payments', 'reviews'];
  const hasProducts = selectedModules.includes('products');
  const hasPayments = selectedModules.includes('payments');
  const hasReviews = selectedModules.includes('reviews');

  const categories = config.productsConfig?.categories || config.categories || ['Electronics', 'Clothing', 'Shoes', 'Accessories'];

  const files = {};

  // 1. Root package.json
  files['package.json'] = JSON.stringify({
    name: slug,
    version: '1.0.0',
    private: true,
    description: `${storeName} - Full-Stack MERN E-Commerce Store`,
    scripts: {
      "install:all": "npm install --prefix client && npm install --prefix server",
      "dev": "node -e \"console.log('Run `cd server && npm run dev` and `cd client && npm run dev` in separate terminals')\"",
      "seed": "npm run seed --prefix server"
    }
  }, null, 2);

  // 2. Root .env.example
  let envExampleContent = `# Database & Port\nPORT=5000\nMONGODB_URI=mongodb://localhost:27017/${slug.replace(/-/g, '_')}_db\nJWT_SECRET=production_jwt_secret_key_change_me\nCLIENT_URL=http://localhost:5173\n`;
  if (hasPayments) {
    envExampleContent += `\n# Razorpay Payment Gateway (Test Mode)\nRAZORPAY_KEY_ID=rzp_test_placeholder_key\nRAZORPAY_KEY_SECRET=rzp_test_placeholder_secret\n`;
  }
  files['.env.example'] = envExampleContent;

  // 3. Root README.md
  files['README.md'] = `# ${storeName}

Generated by Autonomous MERN E-Commerce Code Generator.

## Features Included
- **Core Commerce:** Authentication (JWT), Shopping Cart, Order Management
${hasProducts ? `- **Products Catalog:** Multi-category filtering (${categories.join(', ')}), search, details\n` : ''}${hasPayments ? `- **Payments:** Razorpay Test Mode Checkout\n` : ''}${hasReviews ? `- **Reviews & Ratings:** Customer product feedback & ratings\n` : ''}

## Quick Setup Instructions

1. **Configure Environment Variables:**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your MongoDB connection string and Razorpay test credentials
   \`\`\`

2. **Install Dependencies:**
   \`\`\`bash
   # Server dependencies
   cd server && npm install

   # Client dependencies
   cd ../client && npm install
   \`\`\`

3. **Seed Database with Sample Products:**
   \`\`\`bash
   cd ../server
   npm run seed
   \`\`\`

4. **Start the Application:**
   In terminal 1 (Backend API):
   \`\`\`bash
   cd server
   npm run dev
   # Runs on http://localhost:5000
   \`\`\`

   In terminal 2 (Frontend React + Vite):
   \`\`\`bash
   cd client
   npm run dev
   # Runs on http://localhost:5173
   \`\`\`

## Test User Credentials
- Email: \`customer@demo.com\`
- Password: \`Password@123\`
`;

  // ========================================================
  // SERVER FILES
  // ========================================================

  files['server/package.json'] = JSON.stringify({
    name: `${slug}-server`,
    version: '1.0.0',
    type: 'module',
    main: 'server.js',
    scripts: {
      dev: 'node server.js',
      start: 'node server.js',
      seed: 'node seed.js'
    },
    dependencies: {
      express: '^4.21.2',
      mongoose: '^8.9.5',
      cors: '^2.8.5',
      dotenv: '^16.4.7',
      jsonwebtoken: '^9.0.2',
      bcryptjs: '^2.4.3'
    }
  }, null, 2);

  files['server/models/User.js'] = `import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true, lowercase: true },
  password: { type: String, required: true },
  role: { type: String, enum: ['customer', 'admin'], default: 'customer' }
}, { timestamps: true });

export const User = mongoose.model('User', userSchema);
`;

  files['server/models/Product.js'] = `import mongoose from 'mongoose';

const productSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, default: '' },
  price: { type: Number, required: true },
  category: { type: String, required: true },
  image: { type: String, default: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80' },
  stock: { type: Number, default: 20 },
  rating: { type: Number, default: 5 },
  reviewsCount: { type: Number, default: 0 }
}, { timestamps: true });

export const Product = mongoose.model('Product', productSchema);
`;

  files['server/models/Order.js'] = `import mongoose from 'mongoose';

const orderSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: false },
  customer: {
    name: String,
    email: String,
    address: String,
    city: String,
    postalCode: String
  },
  items: [
    {
      productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
      name: String,
      price: Number,
      quantity: Number
    }
  ],
  totalAmount: { type: Number, required: true },
  paymentMethod: { type: String, default: '${hasPayments ? 'Razorpay' : 'Direct Order'}' },
  paymentStatus: { type: String, default: 'Completed' },
  status: { type: String, default: 'Processing', enum: ['Processing', 'Shipped', 'Delivered', 'Cancelled'] }
}, { timestamps: true });

export const Order = mongoose.model('Order', orderSchema);
`;

  if (hasReviews) {
    files['server/models/Review.js'] = `import mongoose from 'mongoose';

const reviewSchema = new mongoose.Schema({
  productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: false },
  userName: { type: String, required: true },
  rating: { type: Number, required: true, min: 1, max: 5 },
  comment: { type: String, required: true }
}, { timestamps: true });

export const Review = mongoose.model('Review', reviewSchema);
`;
  }

  files['server/middleware/auth.js'] = `import jwt from 'jsonwebtoken';

export const requireAuth = (req, res, next) => {
  const token = req.headers.authorization?.replace('Bearer ', '');
  if (!token) return res.status(401).json({ success: false, message: 'Authorization required' });

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'dev_secret');
    req.user = decoded;
    next();
  } catch (err) {
    return res.status(401).json({ success: false, message: 'Invalid or expired token' });
  }
};
`;

  files['server/routes/auth.js'] = `import { Router } from 'express';
import jwt from 'jsonwebtoken';
import { User } from '../models/User.js';

const router = Router();

router.post('/register', async (req, res) => {
  try {
    const { name, email, password } = req.body;
    const existing = await User.findOne({ email });
    if (existing) return res.status(400).json({ success: false, message: 'Email already exists' });

    const user = await User.create({ name, email, password });
    const token = jwt.sign({ id: user._id, email: user.email }, process.env.JWT_SECRET || 'dev_secret', { expiresIn: '7d' });
    res.status(201).json({ success: true, user: { id: user._id, name: user.name, email: user.email }, token });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email, password });
    if (!user) return res.status(401).json({ success: false, message: 'Invalid credentials' });

    const token = jwt.sign({ id: user._id, email: user.email }, process.env.JWT_SECRET || 'dev_secret', { expiresIn: '7d' });
    res.json({ success: true, user: { id: user._id, name: user.name, email: user.email }, token });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
`;

  files['server/routes/products.js'] = `import { Router } from 'express';
import { Product } from '../models/Product.js';

const router = Router();

router.get('/', async (req, res) => {
  try {
    const { category, search } = req.query;
    const query = {};
    if (category && category !== 'All') query.category = category;
    if (search) query.name = { $regex: search, $options: 'i' };

    const products = await Product.find(query);
    res.json({ success: true, data: products });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

router.get('/:id', async (req, res) => {
  try {
    const product = await Product.findById(req.params.id);
    if (!product) return res.status(404).json({ success: false, message: 'Product not found' });
    res.json({ success: true, data: product });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
`;

  files['server/routes/orders.js'] = `import { Router } from 'express';
import { Order } from '../models/Order.js';

const router = Router();

router.post('/', async (req, res) => {
  try {
    const { customer, items, totalAmount, paymentMethod } = req.body;
    const order = await Order.create({
      customer,
      items,
      totalAmount,
      paymentMethod: paymentMethod || '${hasPayments ? 'Razorpay' : 'Direct Order'}',
      status: 'Processing'
    });
    res.status(201).json({ success: true, data: order });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

router.get('/', async (req, res) => {
  try {
    const orders = await Order.find().sort({ createdAt: -1 });
    res.json({ success: true, data: orders });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
`;

  if (hasPayments) {
    files['server/routes/payments.js'] = `import { Router } from 'express';

const router = Router();

router.post('/razorpay/order', async (req, res) => {
  try {
    const { amount } = req.body;
    // In test mode: return mock Razorpay order id
    res.json({
      success: true,
      orderId: 'order_' + Math.random().toString(36).substring(7),
      amount: amount * 100,
      currency: '${currency}'
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
`;
  }

  if (hasReviews) {
    files['server/routes/reviews.js'] = `import { Router } from 'express';
import { Review } from '../models/Review.js';

const router = Router();

router.get('/product/:productId', async (req, res) => {
  try {
    const reviews = await Review.find({ productId: req.params.productId }).sort({ createdAt: -1 });
    res.json({ success: true, data: reviews });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

router.post('/product/:productId', async (req, res) => {
  try {
    const { userName, rating, comment } = req.body;
    const review = await Review.create({
      productId: req.params.productId,
      userName: userName || 'Verified Customer',
      rating: Number(rating) || 5,
      comment
    });
    res.status(201).json({ success: true, data: review });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
`;
  }

  files['server/seed.js'] = `import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Product } from './models/Product.js';
import { User } from './models/User.js';

dotenv.config();

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/${slug.replace(/-/g, '_')}_db';

const sampleProducts = [
${categories.map((cat, idx) => `  {
    name: '${cat} Essential Pro ${idx + 1}',
    description: 'High-quality premium ${cat.toLowerCase()} built for everyday reliability and superior comfort.',
    price: ${(idx + 1) * 499},
    category: '${cat}',
    image: 'https://images.unsplash.com/photo-${1500000000000 + idx * 100000}?w=500&auto=format&fit=crop&q=80',
    stock: 25,
    rating: 5,
    reviewsCount: 12
  }`).join(',\n')}
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('[Seed] Connected to MongoDB');

    await Product.deleteMany({});
    await User.deleteMany({});

    await Product.insertMany(sampleProducts);
    await User.create({
      name: 'Demo Customer',
      email: 'customer@demo.com',
      password: 'Password@123',
      role: 'customer'
    });

    console.log('[Seed] Success! Seeded sample products and default demo customer.');
    process.exit(0);
  } catch (err) {
    console.error('[Seed] Error:', err.message);
    process.exit(1);
  }
}

seed();
`;

  files['server/server.js'] = `import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import mongoose from 'mongoose';

import authRoutes from './routes/auth.js';
import productRoutes from './routes/products.js';
import orderRoutes from './routes/orders.js';
${hasPayments ? "import paymentRoutes from './routes/payments.js';\n" : ''}${hasReviews ? "import reviewRoutes from './routes/reviews.js';\n" : ''}
dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;
const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/${slug.replace(/-/g, '_')}_db';

app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }));
app.use(express.json());

// Routes
app.use('/api/auth', authRoutes);
app.use('/api/products', productRoutes);
app.use('/api/orders', orderRoutes);
${hasPayments ? "app.use('/api/payments', paymentRoutes);\n" : ''}${hasReviews ? "app.use('/api/reviews', reviewRoutes);\n" : ''}
app.get('/api/health', (req, res) => {
  res.json({ success: true, store: '${storeName}', status: 'operational' });
});

mongoose.connect(MONGO_URI)
  .then(() => {
    console.log('[MongoDB] Connected to database');
    app.listen(PORT, () => {
      console.log(\`[Server] ${storeName} API running on port \${PORT}\`);
    });
  })
  .catch((err) => {
    console.warn('[MongoDB] Running offline mode (DB connection failed):', err.message);
    app.listen(PORT, () => {
      console.log(\`[Server] ${storeName} API running in standalone mode on port \${PORT}\`);
    });
  });
`;

  // ========================================================
  // CLIENT FILES
  // ========================================================

  files['client/package.json'] = JSON.stringify({
    name: `${slug}-client`,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1',
      'react-router-dom': '^6.29.0',
      'lucide-react': '^0.475.0',
      axios: '^1.7.9'
    },
    devDependencies: {
      '@vitejs/plugin-react': '^4.3.4',
      vite: '^6.1.0'
    }
  }, null, 2);

  files['client/vite.config.js'] = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 }
});
`;

  files['client/index.html'] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${storeName}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;

  files['client/src/main.jsx'] = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

  files['client/src/App.jsx'] = `import React, { useState, createContext, useContext, useEffect } from 'react';
import { BrowserRouter, Routes, Route, Link, useNavigate } from 'react-router-dom';

const CartContext = createContext();

export function useCart() {
  return useContext(CartContext);
}

// Sample fallback catalog
const DEFAULT_PRODUCTS = [
${categories.map((c, i) => `  { id: '${i + 1}', name: '${c} Essential Pro', category: '${c}', price: ${(i + 1) * 499}, description: 'Premium ${c} designed with supreme durability and functionality.' }`).join(',\n')}
];

function Navbar() {
  const { cart } = useCart();
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0);

  return (
    <nav style={{ padding: '1rem', borderBottom: '1px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
        <Link to="/" style={{ fontWeight: 'bold', fontSize: '1.25rem', textDecoration: 'none', color: '#111' }}>
          ${storeName}
        </Link>
        <Link to="/products" style={{ textDecoration: 'none', color: '#4b5563' }}>Products</Link>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <Link to="/cart" style={{ textDecoration: 'none', color: '#111', fontWeight: 500 }}>
          Cart ({cartCount})
        </Link>
        <Link to="/profile" style={{ textDecoration: 'none', color: '#4b5563' }}>Profile</Link>
      </div>
    </nav>
  );
}

function HomePage() {
  const navigate = useNavigate();

  return (
    <div style={{ maxWidth: '1000px', margin: '2rem auto', padding: '0 1rem' }}>
      <header style={{ padding: '3rem 2rem', backgroundColor: '#f9fafb', borderRadius: '8px', textAlign: 'center', marginBottom: '3rem' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>Welcome to ${storeName}</h1>
        <p style={{ color: '#4b5563', maxWidth: '600px', margin: '0 auto 1.5rem auto' }}>
          Discover curated quality across our verified product collection.
        </p>
        <button onClick={() => navigate('/products')} style={{ padding: '0.75rem 1.5rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Explore Products
        </button>
      </header>

      <section>
        <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem' }}>Shop by Category</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
          {[${categories.map(c => `'${c}'`).join(', ')}].map(cat => (
            <div key={cat} onClick={() => navigate(\`/products?category=\${cat}\`)} style={{ padding: '1.5rem', border: '1px solid #e5e7eb', borderRadius: '6px', textAlign: 'center', cursor: 'pointer', backgroundColor: '#fff' }}>
              <h3 style={{ margin: 0, fontSize: '1rem' }}>{cat}</h3>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

function ProductsPage() {
  const { addToCart } = useCart();
  const [products] = useState(DEFAULT_PRODUCTS);
  const [selectedCat, setSelectedCat] = useState('All');

  const filtered = selectedCat === 'All' ? products : products.filter(p => p.category === selectedCat);

  return (
    <div style={{ maxWidth: '1000px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1 style={{ marginBottom: '1.5rem' }}>Product Catalog</h1>
      
      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '2rem', flexWrap: 'wrap' }}>
        {['All', ${categories.map(c => `'${c}'`).join(', ')}].map(cat => (
          <button
            key={cat}
            onClick={() => setSelectedCat(cat)}
            style={{
              padding: '0.5rem 1rem',
              borderRadius: '20px',
              border: '1px solid #e5e7eb',
              backgroundColor: selectedCat === cat ? '${themeColor}' : '#fff',
              color: selectedCat === cat ? '#fff' : '#374151',
              cursor: 'pointer'
            }}
          >
            {cat}
          </button>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1.5rem' }}>
        {filtered.map(p => (
          <div key={p.id} style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1rem', backgroundColor: '#fff', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
            <div>
              <span style={{ fontSize: '0.75rem', backgroundColor: '#f3f4f6', padding: '0.2rem 0.5rem', borderRadius: '4px' }}>{p.category}</span>
              <h3 style={{ fontSize: '1.1rem', margin: '0.5rem 0' }}>{p.name}</h3>
              <p style={{ color: '#6b7280', fontSize: '0.875rem' }}>{p.description}</p>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1rem' }}>
              <span style={{ fontWeight: 'bold', fontSize: '1.1rem' }}>${currencySymbol}{p.price}</span>
              <button
                onClick={() => addToCart(p)}
                style={{ padding: '0.5rem 1rem', backgroundColor: '#111827', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
              >
                Add to Cart
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function CartPage() {
  const { cart, updateQuantity, removeFromCart } = useCart();
  const navigate = useNavigate();
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  return (
    <div style={{ maxWidth: '800px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>Shopping Cart</h1>
      {cart.length === 0 ? (
        <div style={{ padding: '3rem', textAlign: 'center', border: '1px dashed #d1d5db', borderRadius: '8px' }}>
          <p>Your shopping cart is empty.</p>
          <button onClick={() => navigate('/products')} style={{ padding: '0.5rem 1rem', cursor: 'pointer' }}>Browse Products</button>
        </div>
      ) : (
        <div>
          <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden', marginBottom: '1.5rem' }}>
            {cart.map(item => (
              <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem', borderBottom: '1px solid #f3f4f6' }}>
                <div>
                  <h4 style={{ margin: 0 }}>{item.name}</h4>
                  <p style={{ margin: '0.25rem 0 0 0', color: '#6b7280', fontSize: '0.875rem' }}>${currencySymbol}{item.price}</p>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <button onClick={() => updateQuantity(item.id, item.quantity - 1)} style={{ padding: '0.25rem 0.5rem' }}>-</button>
                  <span>{item.quantity}</span>
                  <button onClick={() => updateQuantity(item.id, item.quantity + 1)} style={{ padding: '0.25rem 0.5rem' }}>+</button>
                  <button onClick={() => removeFromCart(item.id)} style={{ marginLeft: '1rem', color: '#ef4444', background: 'none', border: 'none', cursor: 'pointer' }}>Remove</button>
                </div>
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem', backgroundColor: '#f9fafb', borderRadius: '8px' }}>
            <div>
              <span style={{ color: '#4b5563' }}>Subtotal: </span>
              <strong style={{ fontSize: '1.25rem' }}>${currencySymbol}{total}</strong>
            </div>
            <button
              onClick={() => navigate('/checkout')}
              style={{ padding: '0.75rem 1.5rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}
            >
              Proceed to Checkout
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function CheckoutPage() {
  const { cart, clearCart } = useCart();
  const navigate = useNavigate();
  const [placed, setPlaced] = useState(false);
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  const handleOrder = (e) => {
    e.preventDefault();
    clearCart();
    setPlaced(true);
  };

  if (placed) {
    return (
      <div style={{ maxWidth: '600px', margin: '4rem auto', textAlign: 'center', padding: '2rem', border: '1px solid #e5e7eb', borderRadius: '8px' }}>
        <h2 style={{ color: '#10b981' }}>Order Confirmed!</h2>
        <p>Thank you for shopping at ${storeName}. Your order has been placed successfully.</p>
        <button onClick={() => navigate('/profile')} style={{ padding: '0.5rem 1rem', marginTop: '1rem', cursor: 'pointer' }}>View in My Orders</button>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '600px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>Checkout</h1>
      <form onSubmit={handleOrder} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <input placeholder="Full Name" defaultValue="Demo Customer" required style={{ padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc' }} />
        <input placeholder="Shipping Address" defaultValue="123 Market St" required style={{ padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc' }} />
        <input placeholder="City" defaultValue="Bangalore" required style={{ padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc' }} />
        
        <div style={{ padding: '1rem', backgroundColor: '#f9fafb', borderRadius: '6px' }}>
          <h4>Payment Method</h4>
          ${hasPayments ? `
          <p style="color: #2383E2; font-weight: bold;">Razorpay Gateway (Test Mode)</p>
          <small style="color: #666;">Configured via RAZORPAY_KEY_ID</small>
          ` : `
          <p style="color: #111;">Direct Order / Cash on Delivery</p>
          `}
          <p style={{ marginTop: '0.5rem' }}>Total Payable: <strong>${currencySymbol}{total}</strong></p>
        </div>

        <button type="submit" style={{ padding: '0.75rem', backgroundColor: '#111827', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>
          ${hasPayments ? 'Pay with Razorpay' : 'Place Order'}
        </button>
      </form>
    </div>
  );
}

function ProfilePage() {
  return (
    <div style={{ maxWidth: '800px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>Customer Profile</h1>
      <div style={{ padding: '1.5rem', border: '1px solid #e5e7eb', borderRadius: '8px', marginBottom: '2rem' }}>
        <h3 style={{ margin: 0 }}>Demo Customer</h3>
        <p style={{ margin: '0.25rem 0 0 0', color: '#6b7280' }}>customer@demo.com</p>
      </div>

      <h2>My Orders</h2>
      <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' }}>
        <div style={{ padding: '1rem', borderBottom: '1px solid #f3f4f6', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <span style={{ fontWeight: 'bold' }}>Order #ORD-8492</span>
            <p style={{ margin: 0, color: '#6b7280', fontSize: '0.875rem' }}>Delivered on Oct 1, 2026</p>
          </div>
          <div>
            <span style={{ backgroundColor: '#ecfdf5', color: '#047857', padding: '0.25rem 0.5rem', borderRadius: '4px', fontSize: '0.75rem' }}>Delivered</span>
            <strong style={{ marginLeft: '1rem' }}>${currencySymbol}998</strong>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function App() {
  const [cart, setCart] = useState([]);

  const addToCart = (product) => {
    setCart(prev => {
      const existing = prev.find(item => item.id === product.id);
      if (existing) {
        return prev.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item);
      }
      return [...prev, { ...product, quantity: 1 }];
    });
  };

  const updateQuantity = (id, quantity) => {
    if (quantity <= 0) {
      removeFromCart(id);
    } else {
      setCart(prev => prev.map(item => item.id === id ? { ...item, quantity } : item));
    }
  };

  const removeFromCart = (id) => {
    setCart(prev => prev.filter(item => item.id !== id));
  };

  const clearCart = () => setCart([]);

  return (
    <CartContext.Provider value={{ cart, addToCart, updateQuantity, removeFromCart, clearCart }}>
      <BrowserRouter>
        <Navbar />
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/products" element={<ProductsPage />} />
          <Route path="/cart" element={<CartPage />} />
          <Route path="/checkout" element={<CheckoutPage />} />
          <Route path="/profile" element={<ProfilePage />} />
        </Routes>
      </BrowserRouter>
    </CartContext.Provider>
  );
}
`;

  // Standalone Client Components & Pages (for modularity)
  files['client/src/components/Navbar.jsx'] = `import React from 'react';
import { Link } from 'react-router-dom';
import { useCart } from '../App.jsx';

export default function Navbar() {
  const { cart } = useCart();
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0);

  return (
    <nav style={{ padding: '1rem', borderBottom: '1px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
        <Link to="/" style={{ fontWeight: 'bold', fontSize: '1.25rem', textDecoration: 'none', color: '#111' }}>
          ${storeName}
        </Link>
        <Link to="/products" style={{ textDecoration: 'none', color: '#4b5563' }}>Products</Link>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <Link to="/cart" style={{ textDecoration: 'none', color: '#111', fontWeight: 500 }}>
          Cart ({cartCount})
        </Link>
        <Link to="/profile" style={{ textDecoration: 'none', color: '#4b5563' }}>Profile</Link>
      </div>
    </nav>
  );
}
`;

  files['client/src/components/ProductCard.jsx'] = `import React from 'react';
import { useCart } from '../App.jsx';

export default function ProductCard({ product }) {
  const { addToCart } = useCart();

  return (
    <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1.25rem', backgroundColor: '#fff', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
      <div>
        <div style={{ fontSize: '0.75rem', color: '#6b7280', textTransform: 'uppercase', marginBottom: '0.25rem' }}>{product.category}</div>
        <h3 style={{ fontSize: '1.1rem', margin: '0 0 0.5rem 0' }}>{product.name}</h3>
        <p style={{ fontSize: '0.875rem', color: '#4b5563', margin: '0 0 1rem 0' }}>{product.description}</p>
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ fontSize: '1.2rem', fontWeight: 'bold' }}>${currencySymbol}{product.price}</span>
        <button onClick={() => addToCart(product)} style={{ padding: '0.5rem 1rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Add to Cart
        </button>
      </div>
    </div>
  );
}
`;

  files['client/src/pages/Home.jsx'] = `import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function Home() {
  const navigate = useNavigate();

  return (
    <div style={{ maxWidth: '1000px', margin: '2rem auto', padding: '0 1rem' }}>
      <header style={{ padding: '3rem 2rem', backgroundColor: '#f9fafb', borderRadius: '8px', textAlign: 'center', marginBottom: '3rem' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>Welcome to ${storeName}</h1>
        <p style={{ color: '#4b5563', maxWidth: '600px', margin: '0 auto 1.5rem auto' }}>
          Discover curated quality across our verified product collection.
        </p>
        <button onClick={() => navigate('/products')} style={{ padding: '0.75rem 1.5rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Explore Products
        </button>
      </header>

      <section>
        <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem' }}>Shop by Category</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
          {[${categories.map(c => `'${c}'`).join(', ')}].map(cat => (
            <div key={cat} onClick={() => navigate(\`/products?category=\${cat}\`)} style={{ padding: '1.5rem', border: '1px solid #e5e7eb', borderRadius: '6px', textAlign: 'center', cursor: 'pointer', backgroundColor: '#fff' }}>
              <h3 style={{ margin: 0, fontSize: '1rem' }}>{cat}</h3>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
`;

  files['client/src/pages/Products.jsx'] = `import React, { useState } from 'react';
import { useCart } from '../App.jsx';
import ProductCard from '../components/ProductCard.jsx';

export default function Products() {
  const { addToCart } = useCart();
  const [selectedCat, setSelectedCat] = useState('All');

  const products = [
${categories.map((c, i) => `    { id: '${i + 1}', name: '${c} Essential Pro', category: '${c}', price: ${(i + 1) * 499}, description: 'Premium ${c} designed with supreme durability and functionality.' }`).join(',\n')}
  ];

  const filtered = selectedCat === 'All' ? products : products.filter(p => p.category === selectedCat);

  return (
    <div style={{ maxWidth: '1000px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1 style={{ marginBottom: '1.5rem' }}>Product Catalog</h1>
      
      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '2rem', flexWrap: 'wrap' }}>
        {['All', ${categories.map(c => `'${c}'`).join(', ')}].map(cat => (
          <button
            key={cat}
            onClick={() => setSelectedCat(cat)}
            style={{
              padding: '0.5rem 1rem',
              borderRadius: '4px',
              border: '1px solid #e5e7eb',
              backgroundColor: selectedCat === cat ? '${themeColor}' : '#fff',
              color: selectedCat === cat ? '#fff' : '#374151',
              cursor: 'pointer'
            }}
          >
            {cat}
          </button>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1.5rem' }}>
        {filtered.map(p => (
          <ProductCard key={p.id} product={p} />
        ))}
      </div>
    </div>
  );
}
`;

  files['client/src/pages/ProductDetails.jsx'] = `import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useCart } from '../App.jsx';

export default function ProductDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { addToCart } = useCart();

  return (
    <div style={{ maxWidth: '800px', margin: '2rem auto', padding: '0 1rem' }}>
      <button onClick={() => navigate(-1)} style={{ marginBottom: '1rem', background: 'none', border: 'none', cursor: 'pointer', color: '#4b5563' }}>
        ← Back to Catalog
      </button>
      <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '2rem', backgroundColor: '#fff' }}>
        <h1>Product Details #{id}</h1>
        <p style={{ color: '#4b5563' }}>High quality craftsmanship crafted for longevity and daily comfort.</p>
        <div style={{ margin: '1.5rem 0', fontSize: '1.5rem', fontWeight: 'bold' }}>${currencySymbol}999</div>
        <button onClick={() => addToCart({ id, name: 'Product #' + id, price: 999 })} style={{ padding: '0.75rem 2rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Add to Cart
        </button>
      </div>
    </div>
  );
}
`;

  files['client/src/pages/Cart.jsx'] = `import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useCart } from '../App.jsx';

export default function Cart() {
  const { cart, updateQuantity, removeFromCart } = useCart();
  const navigate = useNavigate();
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  if (cart.length === 0) {
    return (
      <div style={{ maxWidth: '600px', margin: '4rem auto', textAlign: 'center' }}>
        <h2>Your cart is currently empty</h2>
        <p style={{ color: '#6b7280', marginBottom: '1.5rem' }}>Browse our curated catalog to discover items you love.</p>
        <button onClick={() => navigate('/products')} style={{ padding: '0.75rem 1.5rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Start Shopping
        </button>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '800px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>Shopping Cart</h1>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', margin: '2rem 0' }}>
        {cart.map(item => (
          <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem', border: '1px solid #e5e7eb', borderRadius: '6px', backgroundColor: '#fff' }}>
            <div>
              <h3 style={{ margin: '0 0 0.25rem 0' }}>{item.name}</h3>
              <div style={{ color: '#6b7280' }}>${currencySymbol}{item.price} each</div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <button onClick={() => updateQuantity(item.id, item.quantity - 1)} style={{ padding: '0.25rem 0.5rem', border: '1px solid #ccc', background: '#fff', borderRadius: '4px', cursor: 'pointer' }}>-</button>
                <span>{item.quantity}</span>
                <button onClick={() => updateQuantity(item.id, item.quantity + 1)} style={{ padding: '0.25rem 0.5rem', border: '1px solid #ccc', background: '#fff', borderRadius: '4px', cursor: 'pointer' }}>+</button>
              </div>
              <strong>${currencySymbol}{item.price * item.quantity}</strong>
              <button onClick={() => removeFromCart(item.id)} style={{ color: '#ef4444', background: 'none', border: 'none', cursor: 'pointer' }}>✕</button>
            </div>
          </div>
        ))}
      </div>
      <div style={{ borderTop: '2px solid #e5e7eb', paddingTop: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2>Total: ${currencySymbol}{total}</h2>
        <button onClick={() => navigate('/checkout')} style={{ padding: '0.75rem 2rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '1rem' }}>
          Proceed to Checkout
        </button>
      </div>
    </div>
  );
}
`;

  files['client/src/pages/Checkout.jsx'] = `import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCart } from '../App.jsx';

export default function Checkout() {
  const { cart, clearCart } = useCart();
  const navigate = useNavigate();
  const [success, setSuccess] = useState(false);

  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  const handlePlaceOrder = (e) => {
    e.preventDefault();
    setSuccess(true);
    clearCart();
  };

  if (success) {
    return (
      <div style={{ maxWidth: '600px', margin: '4rem auto', textAlign: 'center', padding: '2rem', border: '1px solid #e5e7eb', borderRadius: '8px', backgroundColor: '#fff' }}>
        <h1 style={{ color: '#10b981' }}>Order Placed Successfully!</h1>
        <p style={{ color: '#4b5563', margin: '1rem 0' }}>Thank you for shopping with ${storeName}. Your order is being processed.</p>
        <button onClick={() => navigate('/')} style={{ padding: '0.75rem 1.5rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Return to Store
        </button>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '600px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>Checkout</h1>
      <form onSubmit={handlePlaceOrder} style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '1.5rem' }}>
        <label>
          Full Name
          <input required type="text" placeholder="John Doe" style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <label>
          Email Address
          <input required type="email" placeholder="john@example.com" style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <label>
          Shipping Address
          <textarea required rows="3" placeholder="123 Market Street, City, ZIP" style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>

        ${hasPayments ? `<div style={{ padding: '1rem', backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '6px', fontSize: '0.875rem', color: '#166534' }}>
          ✓ Razorpay Test Mode Gateway Enabled. Simulated test payments active.
        </div>` : ''}

        <div style={{ margin: '1rem 0', fontSize: '1.25rem', fontWeight: 'bold' }}>
          Order Total: ${currencySymbol}{total}
        </div>

        <button type="submit" style={{ padding: '0.75rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '1rem' }}>
          ${hasPayments ? 'Pay with Razorpay (Test)' : 'Confirm & Place Order'}
        </button>
      </form>
    </div>
  );
}
`;

  files['client/src/pages/Profile.jsx'] = `import React from 'react';

export default function Profile() {
  return (
    <div style={{ maxWidth: '800px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>Customer Account</h1>
      <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1.5rem', backgroundColor: '#fff', marginBottom: '2rem' }}>
        <h3 style={{ margin: '0 0 0.5rem 0' }}>Profile Details</h3>
        <p style={{ margin: 0, color: '#4b5563' }}>Logged in as: <strong>customer@demo.com</strong></p>
        <p style={{ margin: '0.25rem 0 0 0', color: '#4b5563' }}>Account Type: Standard Customer</p>
      </div>

      <h2>Recent Orders</h2>
      <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1rem', backgroundColor: '#fff' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <strong>Order #ORD-9821</strong>
            <div style={{ fontSize: '0.875rem', color: '#6b7280' }}>Delivered recently</div>
          </div>
          <span style={{ backgroundColor: '#ecfdf5', color: '#047857', padding: '0.25rem 0.5rem', borderRadius: '4px', fontSize: '0.75rem' }}>Delivered</span>
        </div>
      </div>
    </div>
  );
}
`;

  files['client/src/pages/Login.jsx'] = `import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function Login() {
  const [email, setEmail] = useState('customer@demo.com');
  const [password, setPassword] = useState('Password@123');
  const navigate = useNavigate();

  const handleLogin = (e) => {
    e.preventDefault();
    navigate('/profile');
  };

  return (
    <div style={{ maxWidth: '400px', margin: '4rem auto', padding: '2rem', border: '1px solid #e5e7eb', borderRadius: '8px', backgroundColor: '#fff' }}>
      <h2>Sign In</h2>
      <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '1rem' }}>
        <label>
          Email
          <input type="email" value={email} onChange={e => setEmail(e.target.value)} required style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <label>
          Password
          <input type="password" value={password} onChange={e => setPassword(e.target.value)} required style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <button type="submit" style={{ padding: '0.75rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Sign In
        </button>
      </form>
    </div>
  );
}
`;

  files['client/src/pages/Register.jsx'] = `import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function Register() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleRegister = (e) => {
    e.preventDefault();
    navigate('/profile');
  };

  return (
    <div style={{ maxWidth: '400px', margin: '4rem auto', padding: '2rem', border: '1px solid #e5e7eb', borderRadius: '8px', backgroundColor: '#fff' }}>
      <h2>Create Account</h2>
      <form onSubmit={handleRegister} style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '1rem' }}>
        <label>
          Full Name
          <input type="text" value={name} onChange={e => setName(e.target.value)} required style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <label>
          Email
          <input type="email" value={email} onChange={e => setEmail(e.target.value)} required style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <label>
          Password
          <input type="password" value={password} onChange={e => setPassword(e.target.value)} required style={{ width: '100%', padding: '0.5rem', marginTop: '0.25rem' }} />
        </label>
        <button type="submit" style={{ padding: '0.75rem', backgroundColor: '${themeColor}', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
          Register
        </button>
      </form>
    </div>
  );
}
`;

  return files;
}

